In [447]:

import requests
import pandas as pd
import numpy as np
import csv
from datetime import datetime


zipcode_file = '../../../downloads/Zips2010_90.xlsx' # data for zipcode city_data_input_file
city_data_input_file = '../../../downloads/Zips2010_90.xlsx'
zip_files_df = pd.read_excel(zipcode_file)
city_data_file_read= pd.read_excel("../../../downloads/tocopycitydata.xlsx")
boroughs_array = pd.Series(['BRONX', 'BROOKLYN', 'MANHATTAN', 'QUEENS', 'STATEN ISLAND'])

city_data_file_read

In [448]:
# main data frame variables 
city_data_file_read

,Unique Key,Created Date,Closed Date,Complaint Type,Incident Zip,Status,Borough
0,37373693,2017-10-06 09:19:56,2017-10-17 16:17:58,ELECTRIC,11218,Closed,BROOKLYN
1,37373694,2017-10-06 21:04:04,2017-10-12 16:34:30,HEAT/HOT WATER,11206,Closed,BROOKLYN
2,37373694,2017-10-06 21:04:04,2017-10-12 16:34:30,HEAT/HOT WATER,11206,Closed,BROOKLYN
3,37373696,2017-10-07 15:32:11,2017-10-12 02:07:48,PLUMBING,11224,Closed,BROOKLYN
4,37373696,2017-10-07 15:32:11,2017-10-12 02:07:48,PLUMBING,11224,Closed,BROOKLYN
5,37373697,2017-10-06 22:01:49,2017-10-19 14:05:58,PLUMBING,11207,Closed,BROOKLYN
6,37373697,2017-10-06 22:01:49,2017-10-19 14:05:58,PLUMBING,11207,Closed,BROOKLYN
7,37373698,2017-10-06 09:26:06,2017-10-11 21:51:16,HEAT/HOT WATER,11436,Closed,QUEENS
8,37373698,2017-10-06 09:26:06,2017-10-11 21:51:16,HEAT/HOT WATER,11436,Closed,QUEENS
9,37373699,2017-10-06 13:32:29,2017-10-13 14:42:51,ELECTRIC,10033,Closed,MANHATTAN
10,37373699,2017-10-06 13:32:29,2017-10-13 14:42:51,ELECTRIC,10033,Closed,MANHATTAN
11,37725654,2017-11-17 09:42:00,2017-11-18 09:55:00,Request Large Bulky Item Collection,11417,Closed,QUEENS
12,37725654,2017-11-17 09:42:00,2017-11-18 09:55:00,Request Large Bulky Item Collection,11417,Closed,QUEENS
13,37725660,2017-11-17 15:17:10,2018-01-03 08:54:39,Taxi Complaint,10013,Closed,MANHATTAN
14,37725661,2017-11-17 18:13:54,2017-12-27 09:04:21,Taxi Complaint,10028,Closed,MANHATTAN
15,37725661,2017-11-17 18:13:54,2017-12-27 09:04:21,Taxi Complaint,10028,Closed,MANHATTAN
16,37373932,2017-10-07 10:05:00,2017-10-14 08:45:00,Noise,10010,Closed,MANHATTAN
17,37373932,2017-10-07 10:05:00,2017-10-14 08:45:00,Noise,10010,Closed,MANHATTAN
18,37373937,2017-10-07 11:13:00,2017-10-13 12:00:00,Sanitation Condition,11208,Closed,BROOKLYN
19,37373937,2017-10-07 11:13:00,2017-10-13 12:00:00,Sanitation Condition,11208,Closed,BROOKLYN
20,37373938,2017-10-06 18:19:00,2017-10-07 12:00:00,Dirty Conditions,11215,Closed,BROOKLYN
21,37373938,2017-10-06 18:19:00,2017-10-07 12:00:00,Dirty Conditions,11215,Closed,BROOKLYN
22,37373939,2017-10-06 17:53:00,2017-10-07 12:00:00,Dirty Conditions,11368,Closed,QUEENS
23,37373939,2017-10-06 17:53:00,2017-10-07 12:00:00,Dirty Conditions,11368,Closed,QUEENS
24,37373941,2017-10-06 14:37:00,2017-10-07 12:00:00,Missed Collection (All Materials),11223,Closed,BROOKLYN
25,37373941,2017-10-06 14:37:00,2017-10-07 12:00:00,Missed Collection (All Materials),11223,Closed,BROOKLYN
26,37373942,2017-10-07 11:58:00,2017-10-11 12:00:00,Missed Collection (All Materials),11378,Closed,QUEENS
27,37373942,2017-10-07 11:58:00,2017-10-11 12:00:00,Missed Collection (All Materials),11378,Closed,QUEENS
28,37373945,2017-10-06 22:03:00,2017-10-18 12:00:00,Dirty Conditions,11229,Closed,BROOKLYN
29,37373945,2017-10-06 22:03:00,2017-10-18 12:00:00,Dirty Conditions,11229,Closed,BROOKLYN
...,...,...,...,...,...,...,...
45482,37377027,2017-10-07 00:00:00,2017-10-16 00:00:00,Rodent,10025,Closed,MANHATTAN
45483,37377028,2017-10-07 00:00:00,2017-10-18 00:00:00,Rodent,11209,Closed,BROOKLYN
45484,37377029,2017-10-07 11:07:51,2017-10-23 09:27:36,GENERAL,10453,Closed,BRONX
45485,37377030,2017-10-06 20:30:37,2017-10-13 10:03:26,GENERAL,11220,Closed,BROOKLYN
45486,37377033,2017-10-07 16:46:02,2017-10-13 02:06:09,HEAT/HOT WATER,11212,Closed,BROOKLYN
45487,37377039,2017-10-06 05:42:50,2017-10-10 02:07:12,HEAT/HOT WATER,10466,Closed,BRONX
45488,37377068,2017-10-07 08:26:00,2017-10-07 12:00:00,Missed Collection (All Materials),11204,Closed,BROOKLYN
45489,37377075,2017-10-07 07:09:40,2017-11-20 00:00:00,Building/Use,11420,Closed,QUEENS
45490,37771990,2017-11-24 10:12:00,2017-11-24 20:54:00,Request Large Bulky Item Collection,11385,Closed,QUEENS
45491,37377079,2017-10-07 14:32:20,2017-10-12 00:00:00,Elevator,11221,Closed,BROOKLYN
45492,37377080,2017-10-07 10:55:50,2017-10-13 00:00:00,General Construction/Plumbing,10309,Closed,STATEN ISLAND
45493,37377081,2017-10-06 14:49:38,2017-10-13 09:58:49,PAINT/PLASTER,11204,Closed,BROOKLYN
45494,37377082,2017-10-06 11:29:18,2017-10-18 07:35:03,PAINT/PLASTER,10302,Closed,STATEN ISLAND
45495,37377084,2017-10-06 13:46:02,2017-11-05 11:39:16,PAINT/PLASTER,10029,Closed,MANHATTAN
45496,37377085,2017-10-06 20:16:21,2017-10-30 09:18:18,PLUMBING,10460,Closed,BRONX
45497,37377086,2017-10-06 14:44:16,2017-10-17 16:33:08,PLUMBING,10458,Closed,BRONX
45498,37772000,2017-11-24 10:39:00,2017-11-25 09:12:00,Request Large Bulky Item Collection,11417,Closed,QUEENS
45499,37377090,2017-10-07 23:01:45,2017-10-22 09:56:02,PLUMBING,10028,Closed,MANHATTAN
45500,37377091,2017-10-07 15:52:43,2017-10-30 16:44:27,SAFETY,11213,Closed,BROOKLYN
45501,37377092,2017-10-07 11:42:57,2017-10-18 21:17:44,UNSANITARY CONDITION,11435,Closed,QUEENS
45502,37377093,2017-10-06 11:20:42,2017-10-23 15:30:23,UNSANITARY CONDITION,10023,Closed,MANHATTAN
45503,37772099,2017-11-24 09:47:36,2017-12-20 07:29:28,Street Sign - Damaged,10312,Closed,STATEN ISLAND
45504,37772105,2017-11-24 07:11:14,2018-01-24 06:21:27,Food Establishment,11354,Closed,QUEENS
45505,37772106,2017-11-24 13:15:35,2017-11-28 15:41:55,Sidewalk Condition,11370,Closed,QUEENS
45506,37772107,2017-11-25 01:29:02,2017-12-18 10:24:06,Curb Condition,10305,Closed,STATEN ISLAND
45507,37772113,2017-11-24 17:42:58,2017-12-04 11:37:31,Sidewalk Condition,11355,Closed,QUEENS
45508,37377094,2017-10-06 15:30:45,2017-10-22 18:21:14,UNSANITARY CONDITION,10460,Closed,BRONX
45509,37377099,2017-10-06 04:39:02,2017-10-23 08:44:51,UNSANITARY CONDITION,10456,Closed,BRONX
45510,37377109,2017-10-07 07:29:00,2017-10-11 00:00:00,Request Large Bulky Item Collection,11229,Closed,BROOKLYN
45511,37377110,2017-10-08 00:52:00,2017-10-13 00:00:00,Request Large Bulky Item Collection,11215,Closed,BROOKLYN

In [ ]:
main_data_dataframe = pd.DataFrame( # drop nas
     {"Unique Key":city_data_file_read["Unique Key"],
        "Created Date":city_data_file_read["Created Date"],
        "Closed Date":city_data_file_read["Closed Date"],
        "Complaint Type":city_data_file_read["Complaint Type"],
        "Zip" : city_data_file_read["Incident Zip"],
        "Status": city_data_file_read["Status"],
        "Borough":city_data_file_read["Borough"]
     }
)
zip_file_df = pd.DataFrame ({
    "Zip": zip_files_df["Incident Zips"],
    "Population": zip_files_df["Population"]
})

In [ ]:
### Outline of Page

In [ ]:
# helper variables

popular_complaints = pd.Series(main_data_dataframe.groupby('Complaint Type').size().sort_values(ascending=False))
top_ten_pop_complaints = pd.Series(popular_complaints[:10])
complaints_tops_names = top_ten_pop_complaints.keys()

In [ ]:
# helper functions placed up top in case they need to be used besides points of primary need



def zipcodes_population_obj(): # has of zip_code file
    obj= {}
    length = len(zip_files_df['Population'] -1)
    pops = zip_files_df['Population']
    zips = zip_files_df['Incident Zips']
    one_array = []
    second_array = []
    for pop_value in pops:
        one_array.append(pop_value)
    for zip_value in zips:
        second_array.append(zip_value)
    for x in range(len(one_array)-1):
        once = one_array[x]
        twice = second_array[x]
        obj[twice] = once
    return obj

def define_base_obj_to_use(): # sets obj to use for most popular complaints. includes zero
    starter_complaints_obj = {}
    for x in complaints_tops_names:
        starter_complaints_obj[x] = 0
    return starter_complaints_obj



def take_in_zip_code_spit_out_population(x): 
    return (zip_file_df['Zip'][x])

In [7]:

### DataFrame Organized By ZipCode
first_zipcode_table = main_data_dataframe.loc[main_data_dataframe.Zip == float(11385)] #["Complaint Type"]
second_zipcode_table = main_data_dataframe.loc[main_data_dataframe.Zip == float(11209)] #["Complaint Type"]
third_zipcode_table = main_data_dataframe.loc[main_data_dataframe.Zip == float(11215)] #["Complaint Type"]
fourth_zipcode_table = main_data_dataframe.loc[main_data_dataframe.Zip == float(11216)] #["Complaint Type"]
fifth_zipcode_table = main_data_dataframe.loc[main_data_dataframe.Zip == float(10456)] #["Complaint Type"]
sixth_complainer_table = main_data_dataframe.loc[main_data_dataframe.Zip == float(10453)] #["Complaint Type"]
seventh_complainer_table = main_data_dataframe.loc[main_data_dataframe.Zip == float(11226)] #["Complaint Type"]
eighth_complainer_table = main_data_dataframe.loc[main_data_dataframe.Zip == float(11213)] #["Complaint Type"]
nine_complainer_table = main_data_dataframe.loc[main_data_dataframe.Zip == float(10467)] #["Complaint Type"]
ten_complainer_table = main_data_dataframe.loc[main_data_dataframe.Zip == float(10452)] #["Complaint Type"]


### Row Values of Complaint Types. made for convenience 
first_zip_complaints =  first_zipcode_table["Complaint Type"]
second_zip_complaints = second_zipcode_table["Complaint Type"]
third_zip_complaints = third_zipcode_table["Complaint Type"]
fourth_zip_complaints = fourth_zipcode_table["Complaint Type"]
fifth_zip_complaints = fifth_zipcode_table["Complaint Type"]
six_zip_complaints = sixth_complainer_table["Complaint Type"]
seventh_zip_complaints = seventh_complainer_table["Complaint Type"]
eigth_zip_complaints = eighth_complainer_table["Complaint Type"]
nine_zip_complaints = nine_complainer_table["Complaint Type"]
tenth_zip_complaints = ten_complainer_table["Complaint Type"]


### DataFrame Organized By Borough

bronxtable = main_data_dataframe.loc[main_data_dataframe.Borough == 'BRONX']
manhattan_table = main_data_dataframe.loc[main_data_dataframe.Borough == 'MANHATTAN']
queens_table = main_data_dataframe.loc[main_data_dataframe.Borough == 'QUEENS']
staten_island_table = main_data_dataframe.loc[main_data_dataframe.Borough == 'STATEN ISLAND']
brooklyn_table = main_data_dataframe.loc[main_data_dataframe.Borough == 'BROOKLYN']
bronx_complaints =  bronxtable["Complaint Type"]

### Row Values of Complaint Types. made for convenience 


manhattan_complaints = manhattan_table["Complaint Type"]
queens_complaints = queens_table["Complaint Type"]
SI_complaints = staten_island_table["Complaint Type"]
brooklyn_complaints = brooklyn_table["Complaint Type"]
bronx_complaints =  bronxtable["Complaint Type"]

'Request Large Bulky Item Collection'

In [8]:
def new_group_boroughs_by_zips():

    borough_list = ["BROOKLYN", "QUEENS", "BRONX", "STATEN ISLAND", "MANHATTAN"]
    borough_zips = {
    "BROOKLYN" : [],
    "QUEENS": [],
    "BRONX": [],
    "STATEN ISLAND": [],
    "MANHATTAN": []
}
    
    for zipcode in bronxtable['Zip']: 
        (borough_zips['BRONX'].append(float(zipcode)))
    for zipcode in manhattan_table['Zip']:
        borough_zips['MANHATTAN'].append(float(zipcode))
    for zipcode in queens_table['Zip']:
        borough_zips['QUEENS'].append(float(zipcode))
    for zipcode in staten_island_table['Zip']:
        borough_zips['STATEN ISLAND'].append(float(zipcode))
    for zipcode in brooklyn_table['Zip']:
        print(zipcode)
        borough_zips['BROOKLYN'].append(float(zipcode))
    return(borough_zips)
   

    
#     return(borough_zips)

In [269]:
# boroughs by zips variables 

brooklyn_zips = pd.Series(new_group_boroughs_by_zips()['BROOKLYN']).unique()
manhattan_zips = pd.Series(new_group_boroughs_by_zips()['MANHATTAN']).unique()
queens_zips = pd.Series(new_group_boroughs_by_zips()['QUEENS']).unique()
si_zips = pd.Series(new_group_boroughs_by_zips()['STATEN ISLAND']).unique()
bronx_zips = pd.Series(new_group_boroughs_by_zips()['BRONX']).unique()

brooklyn_zipcodes_array = pd.Series(brooklyn_zips).dropna().unique()
queens_zipcodes_array = pd.Series(queens_zips).dropna().unique()
bronx_zipcodes_array = pd.Series(bronx_zips).dropna().unique()
manhattan_zipcodes_array = pd.Series(manhattan_zips).dropna().unique()
si_zipcodes_array = pd.Series(si_zips).dropna().unique()

In [12]:

def first_zip_top_complainers(): ####
    complainers_obj = define_base_obj_to_use()
    for x in first_zip_complaints:
        if x not in complaints_tops_names:
            pass
        elif (x in complainers_obj):
            complainers_obj[x] += 1
        else:
            complainers_obj[x] = 1
    return(complainers_obj)



def second_zip_top_complainers():
    for x in second_zip_complaints:
        if x not in complaints_tops_names:
            pass
        elif (x in complainers_obj):
            complainers_obj[x] +=1
        else:
            complainers_obj[x] = 1
    return(complainers_obj)


def third_zip_top_complainers():
    for x in third_zip_complaints:
        if x not in complaints_tops_names:
            pass
        elif (x in complainers_obj):
            complainers_obj[x] +=1
        else:
            complainers_obj[x] = 1
    return(complainers_obj)

def fourth_zip_top_complainers():
    for x in fourth_zip_complaints:
        if x not in complaints_tops_names:
            pass
        elif (x in complainers_obj):
            complainers_obj[x] +=1
        else:
            complainers_obj[x] = 1
    return(complainers_obj)

def fifth_zip_top_complainers():
    for x in fifth_zip_complaints:
        if x not in complaints_tops_names:
            pass
        elif (x in complainers_obj):
            complainers_obj[x] +=1
        else:
            complainers_obj[x] = 1
    return(complainers_obj)

def six_zip_top_complainers():
    for x in six_zip_complaints:
        if x not in complaints_tops_names:
            pass
        elif (x in complainers_obj):
            complainers_obj[x] +=1
        else:
            complainers_obj[x] = 1
    return(complainers_obj)

def seventh_zip_top_complainers():
    for x in seventh_zip_complaints:
        if x not in complaints_tops_names:
            pass
        elif (x in complainers_obj):
            complainers_obj[x] +=1
        else:
            complainers_obj[x] = 1
    return(complainers_obj)

def eight_zip_top_complainers():
    for x in eigth_zip_complaints:
        if x not in complaints_tops_names:
            pass
        elif (x in complainers_obj):
            complainers_obj[x] +=1
        else:
            complainers_obj[x] = 1
    return(complainers_obj)

def nine_zip_top_complainers():
    for x in nine_zip_complaints:
        if x not in complaints_tops_names:
            pass
        elif (x in complainers_obj):
            complainers_obj[x] +=1
        else:
            complainers_obj[x] = 1
    return(complainers_obj)

def ten_zip_top_complainers():
    for x in tenth_zip_complaints:
        if x not in complaints_tops_names:
            pass
        elif (x in complainers_obj):
            complainers_obj[x] +=1
        else:
            complainers_obj[x] = 1
    return(complainers_obj)

In [13]:

one = first_zip_top_complainers()
two = second_zip_top_complainers()
three = third_zip_top_complainers()
four = fourth_zip_top_complainers()
five = fifth_zip_top_complainers()
six = six_zip_top_complainers()
seven = seventh_zip_top_complainers()
eight = eight_zip_top_complainers()
nine = nine_zip_top_complainers()
ten = ten_zip_top_complainers()

In [418]:
top_ten_pop_complaints_keys = top_ten_pop_complaints.keys()

In [430]:
first_complainer_df = pd.DataFrame(  ####
     { "Zip": pop_zip_array[0],
     top_ten_pop_complaints_keys[0]: one[top_ten_pop_complaints_keys[0]],
     top_ten_pop_complaints_keys[1]: one[top_ten_pop_complaints_keys[1]],
     top_ten_pop_complaints_keys[2]: one[top_ten_pop_complaints_keys[2]],
     top_ten_pop_complaints_keys[3]: one[top_ten_pop_complaints_keys[3]],
     top_ten_pop_complaints_keys[4]: one[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[5]: one[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[6]: one[top_ten_pop_complaints_keys[6]],
     top_ten_pop_complaints_keys[7]: one[top_ten_pop_complaints_keys[7]],
     top_ten_pop_complaints_keys[8]: one[top_ten_pop_complaints_keys[8]],
     top_ten_pop_complaints_keys[9]: one[top_ten_pop_complaints_keys[9]],

 }, index={0}
)

second_complainer_df = pd.DataFrame(
     { "Zip": pop_zip_array[1],
     top_ten_pop_complaints_keys[0]: two[top_ten_pop_complaints_keys[0]],
     top_ten_pop_complaints_keys[1]: two[top_ten_pop_complaints_keys[1]],
     top_ten_pop_complaints_keys[2]: two[top_ten_pop_complaints_keys[2]],
     top_ten_pop_complaints_keys[3]: two[top_ten_pop_complaints_keys[3]],
     top_ten_pop_complaints_keys[4]: two[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[5]: two[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[6]: two[top_ten_pop_complaints_keys[6]],
     top_ten_pop_complaints_keys[7]: two[top_ten_pop_complaints_keys[7]],
     top_ten_pop_complaints_keys[8]: two[top_ten_pop_complaints_keys[8]],
     top_ten_pop_complaints_keys[9]: two[top_ten_pop_complaints_keys[9]],

 }, index={1}
)


third_complainer_df = pd.DataFrame(
     { "Zip": pop_zip_array[2],
     top_ten_pop_complaints_keys[0]: three[top_ten_pop_complaints_keys[0]],
     top_ten_pop_complaints_keys[1]: three[top_ten_pop_complaints_keys[1]],
     top_ten_pop_complaints_keys[2]: three[top_ten_pop_complaints_keys[2]],
     top_ten_pop_complaints_keys[3]: three[top_ten_pop_complaints_keys[3]],
     top_ten_pop_complaints_keys[4]: three[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[5]: three[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[6]: three[top_ten_pop_complaints_keys[6]],
     top_ten_pop_complaints_keys[7]: three[top_ten_pop_complaints_keys[7]],
     top_ten_pop_complaints_keys[8]: three[top_ten_pop_complaints_keys[8]],
     top_ten_pop_complaints_keys[9]: three[top_ten_pop_complaints_keys[9]],

 }, index={2}
)


fourth_complainer_df = pd.DataFrame(
     {"Zip": pop_zip_array[3],
     top_ten_pop_complaints_keys[0]: four[top_ten_pop_complaints_keys[0]],
     top_ten_pop_complaints_keys[1]: four[top_ten_pop_complaints_keys[1]],
     top_ten_pop_complaints_keys[2]: four[top_ten_pop_complaints_keys[2]],
     top_ten_pop_complaints_keys[3]: four[top_ten_pop_complaints_keys[3]],
     top_ten_pop_complaints_keys[4]: four[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[5]: four[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[6]: four[top_ten_pop_complaints_keys[6]],
     top_ten_pop_complaints_keys[7]: four[top_ten_pop_complaints_keys[7]],
     top_ten_pop_complaints_keys[8]: four[top_ten_pop_complaints_keys[8]],
     top_ten_pop_complaints_keys[9]: four[top_ten_pop_complaints_keys[9]],

 }, index={3}
)


fifth_complainer_df = pd.DataFrame(
     {"Zip": pop_zip_array[4],
     top_ten_pop_complaints_keys[0]: five[top_ten_pop_complaints_keys[0]],
     top_ten_pop_complaints_keys[1]: five[top_ten_pop_complaints_keys[1]],
     top_ten_pop_complaints_keys[2]: five[top_ten_pop_complaints_keys[2]],
     top_ten_pop_complaints_keys[3]: five[top_ten_pop_complaints_keys[3]],
     top_ten_pop_complaints_keys[4]: five[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[5]: five[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[6]: five[top_ten_pop_complaints_keys[6]],
     top_ten_pop_complaints_keys[7]: five[top_ten_pop_complaints_keys[7]],
     top_ten_pop_complaints_keys[8]: five[top_ten_pop_complaints_keys[8]],
     top_ten_pop_complaints_keys[9]: five[top_ten_pop_complaints_keys[9]],

 }, index={4}
)


sixth_complainer_df = pd.DataFrame(
     {"Zip": pop_zip_array[5],
     top_ten_pop_complaints_keys[0]: six[top_ten_pop_complaints_keys[0]],
     top_ten_pop_complaints_keys[1]: six[top_ten_pop_complaints_keys[1]],
     top_ten_pop_complaints_keys[2]: six[top_ten_pop_complaints_keys[2]],
     top_ten_pop_complaints_keys[3]: six[top_ten_pop_complaints_keys[3]],
     top_ten_pop_complaints_keys[4]: six[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[5]: six[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[6]: six[top_ten_pop_complaints_keys[6]],
     top_ten_pop_complaints_keys[7]: six[top_ten_pop_complaints_keys[7]],
     top_ten_pop_complaints_keys[8]: six[top_ten_pop_complaints_keys[8]],
     top_ten_pop_complaints_keys[9]: six[top_ten_pop_complaints_keys[9]],

 }, index={5}
)

seventh_complainer_df = pd.DataFrame(
     {"Zip": pop_zip_array[6],
     top_ten_pop_complaints_keys[0]: seven[top_ten_pop_complaints_keys[0]],
     top_ten_pop_complaints_keys[1]: seven[top_ten_pop_complaints_keys[1]],
     top_ten_pop_complaints_keys[2]: seven[top_ten_pop_complaints_keys[2]],
     top_ten_pop_complaints_keys[3]: seven[top_ten_pop_complaints_keys[3]],
     top_ten_pop_complaints_keys[4]: seven[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[5]: seven[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[6]: seven[top_ten_pop_complaints_keys[6]],
     top_ten_pop_complaints_keys[7]: seven[top_ten_pop_complaints_keys[7]],
     top_ten_pop_complaints_keys[8]: seven[top_ten_pop_complaints_keys[8]],
     top_ten_pop_complaints_keys[9]: seven[top_ten_pop_complaints_keys[9]],

 }, index={6}
)

eighth_complainer_df = pd.DataFrame(
     {
     "Zip": pop_zip_array[7],
     top_ten_pop_complaints_keys[0]: eight[top_ten_pop_complaints_keys[0]],
     top_ten_pop_complaints_keys[1]: eight[top_ten_pop_complaints_keys[1]],
     top_ten_pop_complaints_keys[2]: eight[top_ten_pop_complaints_keys[2]],
     top_ten_pop_complaints_keys[3]: eight[top_ten_pop_complaints_keys[3]],
     top_ten_pop_complaints_keys[4]: eight[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[5]: eight[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[6]: eight[top_ten_pop_complaints_keys[6]],
     top_ten_pop_complaints_keys[7]: eight[top_ten_pop_complaints_keys[7]],
     top_ten_pop_complaints_keys[8]: eight[top_ten_pop_complaints_keys[8]],
     top_ten_pop_complaints_keys[9]: eight[top_ten_pop_complaints_keys[9]],

 }, index={7}
)

nineth_complainer_df = pd.DataFrame(
     {"Zip": pop_zip_array[8],
     top_ten_pop_complaints_keys[0]: nine[top_ten_pop_complaints_keys[0]],
     top_ten_pop_complaints_keys[1]: nine[top_ten_pop_complaints_keys[1]],
     top_ten_pop_complaints_keys[2]: nine[top_ten_pop_complaints_keys[2]],
     top_ten_pop_complaints_keys[3]: nine[top_ten_pop_complaints_keys[3]],
     top_ten_pop_complaints_keys[4]: nine[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[5]: nine[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[6]: nine[top_ten_pop_complaints_keys[6]],
     top_ten_pop_complaints_keys[7]: nine[top_ten_pop_complaints_keys[7]],
     top_ten_pop_complaints_keys[8]: nine[top_ten_pop_complaints_keys[8]],
     top_ten_pop_complaints_keys[9]: nine[top_ten_pop_complaints_keys[9]],
     "Zip": pop_zip_array[8]
 }, index={8}
)

tenth_complainer_df = pd.DataFrame(
     {'Zip': pop_zip_array[9],
     top_ten_pop_complaints_keys[0]: ten[top_ten_pop_complaints_keys[0]],
     top_ten_pop_complaints_keys[1]: ten[top_ten_pop_complaints_keys[1]],
     top_ten_pop_complaints_keys[2]: ten[top_ten_pop_complaints_keys[2]],
     top_ten_pop_complaints_keys[3]: ten[top_ten_pop_complaints_keys[3]],
     top_ten_pop_complaints_keys[4]: ten[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[5]: ten[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[6]: ten[top_ten_pop_complaints_keys[6]],
     top_ten_pop_complaints_keys[7]: ten[top_ten_pop_complaints_keys[7]],
     top_ten_pop_complaints_keys[8]: ten[top_ten_pop_complaints_keys[8]],
     top_ten_pop_complaints_keys[9]: ten[top_ten_pop_complaints_keys[9]],
 }, index={9}
)

In [431]:
zipcodes_with_top_complaints = first_complainer_df.append([second_complainer_df, third_complainer_df, fourth_complainer_df, fifth_complainer_df, sixth_complainer_df, seventh_complainer_df, eighth_complainer_df, nineth_complainer_df, tenth_complainer_df])

In [432]:
zipcodes_with_top_complaints

,Zip,Request Large Bulky Item Collection,UNSANITARY CONDITION,Noise,PAINT/PLASTER,PLUMBING,Street Condition,DOOR/WINDOW,HEAT/HOT WATER,Street Light Condition,Illegal Parking
0,11385,542,0,37,0,36,36,36,36,5,73
1,11209,614,0,37,72,0,0,0,0,4,37
2,11215,470,0,38,0,0,0,0,0,10,36
3,11216,73,144,41,108,72,72,0,0,5,0
4,10456,0,181,0,72,36,36,73,36,4,0
5,10453,0,145,0,108,72,72,72,36,1,0
6,11226,0,72,0,36,180,180,72,36,6,0
7,11213,36,108,0,109,36,36,180,0,7,0
8,10467,0,108,0,72,72,72,0,0,3,36
9,10452,0,180,0,108,72,72,72,37,1,0

In [433]:






###


####



print(' -------- boroughs time -------')

 -------- boroughs time -------

In [16]:




ordered_borough_row = bronxtable.append([manhattan_table, queens_table, staten_island_table, brooklyn_table])

In [17]:
def bronx_complainers(): ####
    borough_complainers_dict = {'Request Large Bulky Item Collection': 0, 'UNSANITARY CONDITION': 0, 'Noise': 0, 'PAINT/PLASTER': 0, 'PLUMBING': 0, 'Street Condition': 0, 'DOOR/WINDOW': 0, 'HEAT/HOT WATER': 0, 'Street Light Condition': 0, 'Illegal Parking': 0}

    for complaint in bronx_complaints: 
        if complaint not in complaints_tops_names:
            pass
        elif (complaint in borough_complainers_dict and complaint in complaints_tops_names):
            borough_complainers_dict[complaint] +=1
        else:
            borough_complainers_dict[complaint] = 1
    return(borough_complainers_dict)

def queens_complainers(): 
    borough_complainers_dict = {'Request Large Bulky Item Collection': 0, 'UNSANITARY CONDITION': 0, 'Noise': 0, 'PAINT/PLASTER': 0, 'PLUMBING': 0, 'Street Condition': 0, 'DOOR/WINDOW': 0, 'HEAT/HOT WATER': 0, 'Street Light Condition': 0, 'Illegal Parking': 0}
#     borough_complainers_dict = {}
    for complaint in queens_complaints: 
        if complaint not in complaints_tops_names:
            pass
        elif (complaint in borough_complainers_dict and complaint in complaints_tops_names):
            borough_complainers_dict[complaint] +=1
        else:
            borough_complainers_dict[complaint] = 1
    return(borough_complainers_dict)

def manhattan_complainers(): 
    borough_complainers_dict = {'Request Large Bulky Item Collection': 0, 'UNSANITARY CONDITION': 0, 'Noise': 0, 'PAINT/PLASTER': 0, 'PLUMBING': 0, 'Street Condition': 0, 'DOOR/WINDOW': 0, 'HEAT/HOT WATER': 0, 'Street Light Condition': 0, 'Illegal Parking': 0}
#     borough_complainers_dict = {}
    for complaint in manhattan_complaints: 
        if complaint not in complaints_tops_names:
            pass
        elif (complaint in borough_complainers_dict and complaint in complaints_tops_names):
            borough_complainers_dict[complaint] +=1
        else:
            borough_complainers_dict[complaint] = 1
    return(borough_complainers_dict)

def si_complainers(): 
    borough_complainers_dict = {'Request Large Bulky Item Collection': 0, 'UNSANITARY CONDITION': 0, 'Noise': 0, 'PAINT/PLASTER': 0, 'PLUMBING': 0, 'Street Condition': 0, 'DOOR/WINDOW': 0, 'HEAT/HOT WATER': 0, 'Street Light Condition': 0, 'Illegal Parking': 0}
#     borough_complainers_dict = {}
    for complaint in SI_complaints: 
        if complaint not in complaints_tops_names:
            pass
        elif (complaint in borough_complainers_dict and complaint in complaints_tops_names):
            borough_complainers_dict[complaint] +=1
        else:
            borough_complainers_dict[complaint] = 1
    return(borough_complainers_dict)

def brooklyn_complainers(): 
    borough_complainers_dict = {'Request Large Bulky Item Collection': 0, 'UNSANITARY CONDITION': 0, 'Noise': 0, 'PAINT/PLASTER': 0, 'PLUMBING': 0, 'Street Condition': 0, 'DOOR/WINDOW': 0, 'HEAT/HOT WATER': 0, 'Street Light Condition': 0, 'Illegal Parking': 0}
#     borough_complainers_dict = {}
    for complaint in brooklyn_complaints: 
        if complaint not in complaints_tops_names:
            pass
        elif (complaint in borough_complainers_dict and complaint in complaints_tops_names):
            borough_complainers_dict[complaint] +=1
        else:
            borough_complainers_dict[complaint] = 1
    return(borough_complainers_dict)

In [18]:
bronx_complainers_var = bronx_complainers()
queens_complainers_var = queens_complainers()
manhattan_complainers_var = manhattan_complainers()
si_complainers_var = si_complainers()
brooklyn_complainers_var = brooklyn_complainers()

In [438]:
 bronx_complainer_df = pd.DataFrame(
     {'Borough': boroughs_array[0],
     top_ten_pop_complaints_keys[0]: bronx_complainers_var[top_ten_pop_complaints_keys[0]],
     top_ten_pop_complaints_keys[1]: bronx_complainers_var[top_ten_pop_complaints_keys[1]],
     top_ten_pop_complaints_keys[2]: bronx_complainers_var[top_ten_pop_complaints_keys[2]],
     top_ten_pop_complaints_keys[3]: bronx_complainers_var[top_ten_pop_complaints_keys[3]],
     top_ten_pop_complaints_keys[4]: bronx_complainers_var[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[5]: bronx_complainers_var[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[6]: bronx_complainers_var[top_ten_pop_complaints_keys[6]],
     top_ten_pop_complaints_keys[7]: bronx_complainers_var[top_ten_pop_complaints_keys[7]],
     top_ten_pop_complaints_keys[8]: bronx_complainers_var[top_ten_pop_complaints_keys[8]],
     top_ten_pop_complaints_keys[9]: bronx_complainers_var[top_ten_pop_complaints_keys[9]],
 }, index={0}
)

 brooklyn_complainer_df = pd.DataFrame(
     {'Borough': boroughs_array[1],
     top_ten_pop_complaints_keys[0]: brooklyn_complainers_var[top_ten_pop_complaints_keys[0]],
     top_ten_pop_complaints_keys[1]: brooklyn_complainers_var[top_ten_pop_complaints_keys[1]],
     top_ten_pop_complaints_keys[2]: brooklyn_complainers_var[top_ten_pop_complaints_keys[2]],
     top_ten_pop_complaints_keys[3]: brooklyn_complainers_var[top_ten_pop_complaints_keys[3]],
     top_ten_pop_complaints_keys[4]: brooklyn_complainers_var[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[5]: brooklyn_complainers_var[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[6]: brooklyn_complainers_var[top_ten_pop_complaints_keys[6]],
     top_ten_pop_complaints_keys[7]: brooklyn_complainers_var[top_ten_pop_complaints_keys[7]],
     top_ten_pop_complaints_keys[8]: brooklyn_complainers_var[top_ten_pop_complaints_keys[8]],
     top_ten_pop_complaints_keys[9]: brooklyn_complainers_var[top_ten_pop_complaints_keys[9]],
 }, index={1}
)

 manhattan_complainer_df = pd.DataFrame(
     {'Borough': boroughs_array[2],
     top_ten_pop_complaints_keys[0]: manhattan_complainers_var[top_ten_pop_complaints_keys[0]],
     top_ten_pop_complaints_keys[1]: manhattan_complainers_var[top_ten_pop_complaints_keys[1]],
     top_ten_pop_complaints_keys[2]: manhattan_complainers_var[top_ten_pop_complaints_keys[2]],
     top_ten_pop_complaints_keys[3]: manhattan_complainers_var[top_ten_pop_complaints_keys[3]],
     top_ten_pop_complaints_keys[4]: manhattan_complainers_var[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[5]: manhattan_complainers_var[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[6]: manhattan_complainers_var[top_ten_pop_complaints_keys[6]],
     top_ten_pop_complaints_keys[7]: manhattan_complainers_var[top_ten_pop_complaints_keys[7]],
     top_ten_pop_complaints_keys[8]: manhattan_complainers_var[top_ten_pop_complaints_keys[8]],
     top_ten_pop_complaints_keys[9]: manhattan_complainers_var[top_ten_pop_complaints_keys[9]],
 }, index={2}
)

 queens_complainer_df = pd.DataFrame(
     {'Borough': boroughs_array[3],
     top_ten_pop_complaints_keys[0]: queens_complainers_var[top_ten_pop_complaints_keys[0]],
     top_ten_pop_complaints_keys[1]: queens_complainers_var[top_ten_pop_complaints_keys[1]],
     top_ten_pop_complaints_keys[2]: queens_complainers_var[top_ten_pop_complaints_keys[2]],
     top_ten_pop_complaints_keys[3]: queens_complainers_var[top_ten_pop_complaints_keys[3]],
     top_ten_pop_complaints_keys[4]: queens_complainers_var[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[5]: queens_complainers_var[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[6]: queens_complainers_var[top_ten_pop_complaints_keys[6]],
     top_ten_pop_complaints_keys[7]: queens_complainers_var[top_ten_pop_complaints_keys[7]],
     top_ten_pop_complaints_keys[8]: queens_complainers_var[top_ten_pop_complaints_keys[8]],
     top_ten_pop_complaints_keys[9]: queens_complainers_var[top_ten_pop_complaints_keys[9]],
 }, index={3}
)

 staten_island_complainer_df = pd.DataFrame(
     {'Borough': boroughs_array[4],
     top_ten_pop_complaints_keys[0]: si_complainers_var[top_ten_pop_complaints_keys[0]],
     top_ten_pop_complaints_keys[1]: si_complainers_var[top_ten_pop_complaints_keys[1]],
     top_ten_pop_complaints_keys[2]: si_complainers_var[top_ten_pop_complaints_keys[2]],
     top_ten_pop_complaints_keys[3]: si_complainers_var[top_ten_pop_complaints_keys[3]],
     top_ten_pop_complaints_keys[4]: si_complainers_var[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[5]: si_complainers_var[top_ten_pop_complaints_keys[4]],
     top_ten_pop_complaints_keys[6]: si_complainers_var[top_ten_pop_complaints_keys[6]],
     top_ten_pop_complaints_keys[7]: si_complainers_var[top_ten_pop_complaints_keys[7]],
     top_ten_pop_complaints_keys[8]: si_complainers_var[top_ten_pop_complaints_keys[8]],
     top_ten_pop_complaints_keys[9]: si_complainers_var[top_ten_pop_complaints_keys[9]],
 }, index={4}
)
borough_with_complaints = bronx_complainer_df.append([brooklyn_complainer_df, manhattan_complainer_df, queens_complainer_df, staten_island_complainer_df])

In [436]:





#######

# complainer- index

,Borough,Request Large Bulky Item Collection,UNSANITARY CONDITION,Noise,PAINT/PLASTER,PLUMBING,Street Condition,DOOR/WINDOW,HEAT/HOT WATER,Street Light Condition,Illegal Parking
0,BRONX,326,1319,110,955,723,723,541,368,416,38
1,BROOKLYN,2099,1315,787,686,758,758,649,434,312,655
2,MANHATTAN,108,723,1059,650,471,471,252,324,188,111
3,QUEENS,2129,487,538,216,433,433,108,289,307,438
4,STATEN ISLAND,109,73,146,73,37,37,0,0,43,3

In [355]:
def count_brooklyn_people():
    zip_code_population_dictionary = zipcodes_population_obj()
    borough_counter = 0
    for x in brooklyn_zipcodes_array:
        safe_num = take_in_zip_code_spit_out_population(x)
        borough_counter += safe_num
    return(borough_counter)
    


def count_queens_people():
    zip_code_population_dictionary = zipcodes_population_obj()
    borough_counter = 0 
    for x in queens_zipcodes_array:
        safe_num = take_in_zip_code_spit_out_population(x)
        borough_counter += safe_num
    return(borough_counter)



def count_bronx_people():
    zip_code_population_dictionary = zipcodes_population_obj()
    borough_counter = 0
    for x in bronx_zipcodes_array:
        safe_num = take_in_zip_code_spit_out_population(x)
        borough_counter += safe_num
    return(borough_counter) 


def count_manhattan_people():
    zip_code_population_dictionary = zipcodes_population_obj()
    borough_counter = 0
    for x in manhattan_zipcodes_array:
        safe_num = take_in_zip_code_spit_out_population(x)
        borough_counter += safe_num
    return(borough_counter) 


def count_si_people():
    zip_code_population_dictionary = zipcodes_population_obj()
    borough_counter = 0
    for x in si_zipcodes_array:
        safe_num = take_in_zip_code_spit_out_population(x)
        borough_counter += safe_num
    return(borough_counter)

In [376]:
si_people = count_si_people()
manhattan_people = count_manhattan_people()
brooklyn_people = count_brooklyn_people()
bronx_people = count_bronx_people()
queens_people = count_queens_people()
total_complaints_borough = city_data_file_read.groupby("Borough").size().to_dict()

{'BRONX': 8699,
 'BROOKLYN': 14437,
 'Borough': 17,
 'MANHATTAN': 7738,
 'QUEENS': 11108,
 'STATEN ISLAND': 2061,
 'Unspecified': 973}

In [379]:
population_obj ={
    "BROOKLYN": brooklyn_people,
    "QUEENS": queens_people,
    "BRONX": bronx_people,
    "STATEN ISLAND": si_people,
    "MANHATTAN": manhattan_people
}


population_df = pd.DataFrame(
    {
        "BROOKLYN" : population_obj['BROOKLYN'],
        "QUEENS": population_obj['QUEENS'],
        "BRONX": population_obj['BRONX'],
        "STATEN ISLAND": population_obj['STATEN ISLAND'],
        "MANHATTAN": population_obj['MANHATTAN'],
    }, index={0}
)

In [445]:

complainer_totals = {
    'BROOKLYN': int(total_complaints_borough['BROOKLYN']),
    'QUEENS': int(total_complaints_borough['QUEENS']),
    'BRONX': int(total_complaints_borough['BRONX']),
    'STATEN ISLAND': int(total_complaints_borough['STATEN ISLAND']),
    'MANHATTAN': int(total_complaints_borough['MANHATTAN'])    
}

brooklyn_populace = pd.DataFrame( ## brooklyn 
    {
        "Borough": "BROOKLYN",
        "Complainer Totals": complainer_totals["BROOKLYN"], 
        "Population": brooklyn_people, 
        "Complainer-Index": complainer_totals["BROOKLYN"]/int(brooklyn_people)
    }, index={0}
)


queens_populace = pd.DataFrame( ## queens 
    {
        "Borough": "QUEENS",
        "Complainer Totals": complainer_totals["QUEENS"], 
        "Population": queens_people, 
        "Complainer-Index": complainer_totals["QUEENS"]/int(queens_people)
        
        
    }, index={1}
)

bronx_populace = pd.DataFrame( ## bronx 
    {
        "Borough": "BRONX",
        "Complainer Totals": complainer_totals["BRONX"], 
        "Population": bronx_people, 
        "Complainer-Index": complainer_totals["BRONX"]/int(bronx_people)
        
    }, index={2}
)

si_populace = pd.DataFrame( ## staten island 
    {
        "Borough": "STATEN ISLAND",
        "Complainer Totals": complainer_totals["STATEN ISLAND"], 
        "Population": si_people,
        "Complainer-Index": complainer_totals["STATEN ISLAND"]/int(si_people)
        
    }, index={3}
)

manhattan_populace = pd.DataFrame( ## staten island 
    {
        "Borough": "MANHATTAN",
        "Complainer Totals": total_complaints_borough["MANHATTAN"], 
        "Population": manhattan_people, 
        "Complainer-Index": complainer_totals["MANHATTAN"]/int(manhattan_people)
        
    }, index={4}
)
all_boroughs = brooklyn_populace.append([queens_populace, bronx_populace, si_populace, manhattan_populace])

In [392]:
#### Organized Data

In [442]:

# Complaints-Index 

all_boroughs

         Borough  Complainer Totals  Population  Complainer-Index
0       BROOKLYN              14437     1371441          0.010527
1         QUEENS              11108     2211810          0.005022
2          BRONX               8699      819049          0.010621
3  STATEN ISLAND               2061      388342          0.005307
4      MANHATTAN               7738     1295022          0.005975

6085664

In [443]:
# Complaints by Zip Code
zipcodes_with_top_complaints

,Zip,Request Large Bulky Item Collection,UNSANITARY CONDITION,Noise,PAINT/PLASTER,PLUMBING,Street Condition,DOOR/WINDOW,HEAT/HOT WATER,Street Light Condition,Illegal Parking
0,11385,542,0,37,0,36,36,36,36,5,73
1,11209,614,0,37,72,0,0,0,0,4,37
2,11215,470,0,38,0,0,0,0,0,10,36
3,11216,73,144,41,108,72,72,0,0,5,0
4,10456,0,181,0,72,36,36,73,36,4,0
5,10453,0,145,0,108,72,72,72,36,1,0
6,11226,0,72,0,36,180,180,72,36,6,0
7,11213,36,108,0,109,36,36,180,0,7,0
8,10467,0,108,0,72,72,72,0,0,3,36
9,10452,0,180,0,108,72,72,72,37,1,0

In [444]:
# Complaints by Borough

borough_with_complaints

,Borough,Request Large Bulky Item Collection,UNSANITARY CONDITION,Noise,PAINT/PLASTER,PLUMBING,Street Condition,DOOR/WINDOW,HEAT/HOT WATER,Street Light Condition,Illegal Parking
0,BRONX,326,1319,110,955,723,723,541,368,416,38
1,BROOKLYN,2099,1315,787,686,758,758,649,434,312,655
2,MANHATTAN,108,723,1059,650,471,471,252,324,188,111
3,QUEENS,2129,487,538,216,433,433,108,289,307,438
4,STATEN ISLAND,109,73,146,73,37,37,0,0,43,3

In [ ]:
#### 

## Assumptions

# Using the 2010 Zip Code Data. 

# Things still to be addressed (unspecified). 
# Following up from the outline 
# What I wish I had done
# the gap in population:6085664. Varies fron a more rough approximation of the 8 million in 2010 within NYC